### ISSUE TITLE
Add intro to homepage

### ISSUE THREAD

**Issue by danielnemenyi** [danielnemenyi/mad-spinning-top#18]
Should add short intro copy to homepage. Not sure if it's been sent over already?

https://mad-spinning-top.netlify.app/

Also comments on general homepage copy welcome! ("What's this all about?")? 

Funders logos also need to be mentioned see #3

**Comment by toupiefolle** [comment]
Hi Daniel,
I think I have logged on to Github OK. 
Re the short intro copy for the homepage, I sent this, which we can use. I believe you asked for copy for the top and bottom of the page.

top
December 1973 saw the publication of issue 13 of the journal _Recherches_, founded among others by activist and philosopher Félix Guattari in 1965. The issue was the outcome of a collective project undertaken by members of CERFI (Centre for Institutional Research, Education and Formation) on ‘collective equipment’, and bore the title The Genealogy of Capital: the Equipments of Power. These pages offer an account of a research project focused on Recherches 13, including a focus on the conceptual apparatuses it deployed, the multiple contexts surrounding the issue, and the research process involved.  


bottom

‘La toupie folle’ (the mad spinning top) is the familiar name we have given to a research project funded by a Small Grant from the British Academy and the Leverhulme Trust, carried out by Professor Patrick ffrench at King’s College London with Dr Susana Caló, Visiting Research Fellow at King’s (see about page for further details). May 2022. 

Re the homepage, I would prefer not to have the question 'What is this all about?', and to have the intro (see above) right at the top below the title 'Mad Spinning Top'. I would also prefer if the landing page were the blog page rather than the node map, as I'm calling it. 

see below (3) on logos.

P

**Comment by danielnemenyi** [comment]
Brilliant, thanks.

**Comment by danielnemenyi** [comment]
- Add intro to homepage and footer: 8ef64b9
- Remove node graph from homepage to /nodes: 6e2a327 
- Move blog roll to homepage: 0376b71

Resolves issue.
